[package]
name = "sonicStore"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
tokio ={ version = "1", features = ["full"]}
clap ={ version = "4.5.55"}


[dev-dependencies]
 anyhow = "1"
 
 